
--=================================================================
--####################	DATA BASE SAMU ONLINE #####################
--####################	CRIADO EM 26/09/2014  #####################
--=================================================================

--============================
--  TABELA RECURSO
--============================

CREATE TABLE RECURSO (
    IDRECURSO 	SERIAL 		NOT NULL,
    NOME 	VARCHAR(35)	NOT NULL,
    DESCRICAO 	VARCHAR(200) 	NOT NULL,
    CONSTRAINT PK_IDRECURSO PRIMARY KEY (IDRECURSO)
);

--============================
--  TABELA PERFIL
--============================

CREATE TABLE PERFIL(
    IDPERFIL 	SERIAL 		NOT NULL,
    NOME 	VARCHAR(35) 	NOT NULL,
    DESCRICAO 	VARCHAR(200) 	NOT NULL,
    CONSTRAINT PK_IDPERFIL PRIMARY KEY (IDPERFIL)
);

--============================
--  TABELA PERFIL_RECURSO
--============================

CREATE TABLE PERFIL_RECURSO(
    IDPERFIL_RECURSO 	SERIAL 		NOT NULL,
    PERFIL_IDPERFIL 	INTEGER 	NOT NULL,
    RECURSO_IDRECURSO 	INTEGER 	NOT NULL,
    CONSTRAINT PK_IDPERFIL_RECURSO PRIMARY KEY(IDPERFIL_RECURSO),
    CONSTRAINT FK_PERFIL_IDPERFIL FOREIGN KEY(PERFIL_IDPERFIL) REFERENCES PERFIL(IDPERFIL)
);


--=====================================
-- TABELA BASE
--=====================================

CREATE TABLE BASE(
    IDBASE SERIAL                                       NOT NULL,
    CODIGO                                  INTEGER     NOT NULL,
    NOME                                    VARCHAR(30) NOT NULL,
    DESCRICAO                               VARCHAR(100) NOT NULL,
    CONSTRAINT PK_IDBASE PRIMARY KEY (IDBASE)
);


--============================
--  TABELA VIATURA
--============================

CREATE TABLE VIATURA(
    IDVIATURA                   SERIAL 		NOT NULL,
    BASE_IDBASE                 INTEGER         NOT NULL,
    CODIGO 			INTEGER 	NOT NULL,
    PLACA 			VARCHAR(8) 	NOT NULL,
    MODELO 			VARCHAR(40)     NOT NULL,
    SKYPE 			VARCHAR(50)     NOT NULL,
    TIPO_VIATURA                VARCHAR(3)      NOT NULL,
    CONSTRAINT PK_IDVIATURA PRIMARY KEY(IDVIATURA),
    CONSTRAINT FK_VIATURA_IDVIATURA FOREIGN KEY (BASE_IDBASE) REFERENCES BASE(IDBASE)
);

--===============================
--  TABELA LOGIN_FUNCIONARIO
--===============================

CREATE TABLE LOGIN_FUNCIONARIO(
    IDLOGIN_FUNCIONARIO 	SERIAL 		NOT NULL,
    PERFIL_IDPERFIL             INTEGER 	NOT NULL,
    NOME 			VARCHAR(70) 	NOT NULL,
    USUARIO                     VARCHAR(30) 	NOT NULL,
    SENHA 			VARCHAR(32) 	NOT NULL,
    CPF 			VARCHAR(11) 	NOT NULL,
    SITUACAO 			INTEGER 	NOT NULL,
    SKYPE 			VARCHAR(50) 	NOT NULL,
    EMAIL 			VARCHAR(60) 	NOT NULL,
    CONSTRAINT PK_IDLOGIN_FUNCIONARIO PRIMARY KEY(IDLOGIN_FUNCIONARIO),
    CONSTRAINT FK_PERFIL_IDPERFIL FOREIGN KEY (PERFIL_IDPERFIL) REFERENCES PERFIL(IDPERFIL),
    CONSTRAINT UN_USUARIO UNIQUE (USUARIO)
);

--==============================
-- TABELA FUNCIONARIO VIATURA
--==============================

CREATE TABLE FUNCIONARIO_VIATURA_BASE(
    IDFUNCIONARIO_VIATURA_BASE			SERIAL 		NOT NULL,
    BASE_IDBASE                                 INTEGER         NULL,
    LOGIN_FUNCIONARIO_IDLOGIN_FUNCIONARIO 	INTEGER 	NOT NULL,
    DATA_HORA_REGISTRO 				TIMESTAMP 	NOT NULL,
    ENTRADA_SAIDA 				CHAR 		NOT NULL,
    CONSTRAINT PK_IDFUNCIONARIO_VIATURA PRIMARY KEY (IDFUNCIONARIO_VIATURA_BASE),
    CONSTRAINT FK_FUNCIONARIO_VIATURA_BASE FOREIGN KEY (BASE_IDBASE) REFERENCES BASE (IDBASE),
    CONSTRAINT FK_LOGIN_FUNC_IDLOGIN FOREIGN KEY (LOGIN_FUNCIONARIO_IDLOGIN_FUNCIONARIO) REFERENCES LOGIN_FUNCIONARIO(IDLOGIN_FUNCIONARIO)
);


--======================
--  TABELA FICHA APH
--======================

CREATE TABLE FICHA_APH(
    IDFICHA_APH 		SERIAL 		NOT NULL,
    HORA_TRANSMISSAO 		VARCHAR(5) 	NOT NULL,
    HORA_CHEGADA_LOCAL 		VARCHAR(5) 	NOT NULL,
    HORA_SAIDA_LOCAL 		VARCHAR(5) 	NOT NULL,
    HORA_CHEGADA_HOSPITAL 	VARCHAR(5) 	NOT NULL,
    HORA_LIGACAO 		VARCHAR(5) 	NOT NULL,
    DATA_HORA_REGISTRO_FICHA 	TimeStamp(5) 	NOT NULL,
    PRODUTOS_UTILIZADOS 	VARCHAR(800)    NOT NULL,
    CONSTRAINT PK_IDFICHA_APH PRIMARY KEY (IDFICHA_APH)
);

--======================
-- TABELA SOLICITANTE
--======================

CREATE TABLE SOLICITANTE(
    IDSOLICITANTE 		SERIAL		NOT NULL,
    TELEFONE 			VARCHAR(14) 	NOT NULL,
    NOME 			VARCHAR(70) 	NOT NULL,
    CIDADE 			VARCHAR(30) 	NOT NULL,
    BAIRRO 			VARCHAR(35) 	NOT NULL,
    ENDERECO 			VARCHAR(70) 	NOT NULL,
    PONTO_REFERENCIA            VARCHAR(50) 	NULL,
    CONSTRAINT PK_IDSOLICITANTE PRIMARY KEY (IDSOLICITANTE)
);

--======================
--  TABLE ATENDIMENTO
--======================

CREATE TABLE ATENDIMENTO(
    IDATENDIMENTO 			SERIAL 		NOT NULL,
    CODIGO_ATENDIMENTO 			BIGINT          NOT NULL,
    FICHA_APH_IDFICHA_APH 		INTEGER 	NULL ,
    SOLICITANTE_IDSOLICITANTE           INTEGER     	NULL ,
    STATUS_ATENDIMENTO 			INTEGER      	NOT NULL,
    DATA_ATENDIMENTO 			DATE 		NOT NULL,
    MOTIVO 				VARCHAR(200)    NOT NULL,
    TIPO_LIGACAO 			CHAR	 	NOT NULL,
    CONSTRAINT PK_IDATENDIMENTO PRIMARY KEY (IDATENDIMENTO),
    CONSTRAINT FK_FICHA_APH_IDFICHA FOREIGN KEY (FICHA_APH_IDFICHA_APH) REFERENCES FICHA_APH (IDFICHA_APH),
    CONSTRAINT FK_SOLICITANTE_IDSOLI FOREIGN KEY (SOLICITANTE_IDSOLICITANTE) REFERENCES SOLICITANTE (IDSOLICITANTE)
);

--======================
-- TABELA PACIENTE
--======================

CREATE TABLE PACIENTE(
    IDPACIENTE 			SERIAL 		NOT NULL,
    ATENDIMENTO_IDATENDIMENTO 	INTEGER 	NOT NULL,
    NOME 			VARCHAR(70)     NOT NULL,
    DATA_NASCIMENTO 		DATE            NOT NULL,
    SEXO 			CHAR 		NOT NULL,
    CONSTRAINT PK_IDPACIENTE PRIMARY KEY (IDPACIENTE),
    CONSTRAINT FK_ATENDIMENTO_PACIENTE FOREIGN KEY (ATENDIMENTO_IDATENDIMENTO) REFERENCES ATENDIMENTO (IDATENDIMENTO)
);

--===========================
-- TABELA ATENDIMENTO VIATURA
--===========================

CREATE TABLE ATENDIMENTO_VIATURA(
    IDATENDIMENTO_VIATURA 	SERIAL 		NOT NULL,
    ATENDIMENTO_IDATENDIMENTO 	INTEGER 	NOT NULL,
    VIATURA_IDVIATURA 		INTEGER 	NOT NULL,
    CONSTRAINT PK_IDATENDIMENTO_VIATURA PRIMARY KEY (IDATENDIMENTO_VIATURA),
    CONSTRAINT FK_ATENDIMENTO_VIATURA FOREIGN KEY (ATENDIMENTO_IDATENDIMENTO) REFERENCES ATENDIMENTO (IDATENDIMENTO)
);

--=====================================
-- TABELA LOGIN FUNCIONARIO ATNDIMENTO
--=====================================

CREATE TABLE LOGIN_FUNCIONARIO_ATENDIMENTO(
    IDLOGIN_FUNCIONARIO_ATENDIMENTO 		SERIAL 		NOT NULL,
    LOGIN_FUNCIONARIO_IDLOGIN_FUNCIONARIO 	INTEGER 	NOT NULL,
    ATENDIMENTO_IDATENDIMENTO 			INTEGER 	NOT NULL,
    CONSTRAINT PK_IDLOGIN_FUNC_ATEN PRIMARY KEY (IDLOGIN_FUNCIONARIO_ATENDIMENTO),
    CONSTRAINT FK_LOGIN_ATENDIMENTO FOREIGN KEY (LOGIN_FUNCIONARIO_IDLOGIN_FUNCIONARIO) REFERENCES LOGIN_FUNCIONARIO (IDLOGIN_FUNCIONARIO),
    CONSTRAINT FK_ATENDIMENTO_LOGIN FOREIGN KEY (ATENDIMENTO_IDATENDIMENTO) REFERENCES ATENDIMENTO (IDATENDIMENTO)
);

--=================================================================
--####################   FIM SCRIPT DATA BASE 	###################
--#################################################################
--=================================================================
